# images
images:
  amf:
    repository: free5gc/amf
    tag: latest
  smf:
    repository: free5gc/smf
    tag: latest
  upf:
    repository: free5gc/upf
    tag: latest

imagePullPolicy: IfNotPresent

# AMF configuration
amf:
  replicaCount: 1
  port: 7777
  config: |
    {
      "sbi": { "scheme": "http", "ipv4": "0.0.0.0", "port": 7777 },
      "smf": { "address": "{{ include \"minimal5gc.fullname\" . }}-smf", "port": 7778 }
    }

# SMF configuration
smf:
  replicaCount: 1
  port: 7778
  config: |
    {
      "sbi": { "scheme": "http", "ipv4": "0.0.0.0", "port": 7778 },
      "amf": { "address": "{{ include \"minimal5gc.fullname\" . }}-amf", "port": 7777 },
      "upf": { "address": "{{ include \"minimal5gc.fullname\" . }}-upf", "port": 8805 }
    }

# UPF configuration
upf:
  replicaCount: 1
  port: 8805
  config: |
    {
      "sbi": { "scheme": "http", "ipv4": "0.0.0.0", "port": 8805 }
      # add PFCP, GTP configurations as needed
    }
