apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  namespace: 5gc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
        - name: amf
          image: towards5gs/free5gc-amf:v3.2.1
          ports:
            - containerPort: 38412
          volumeMounts:
            - name: amf-config
              mountPath: /free5gc/config/amfcfg.yaml
              subPath: amfcfg.yaml
      volumes:
        - name: amf-config
          configMap:
            name: amf-config
