apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  namespace: 5gc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
      - name: amf
        image: free5gc/amf:v1.0.0
        ports:
        - containerPort: 38412