apiVersion: v1
kind: ConfigMap
metadata:
  name: upf-config
  namespace: 5gc
data:
  upfcfg.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration
    configuration:
      pfcp:
        addr: 127.0.0.8
      gtpu:
        addr: 127.0.0.8
