apiVersion: v1
kind: Service
metadata:
  name: {{ include "minimal5gc.fullname" . }}-upf
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.upf.port }}
      targetPort: {{ .Values.upf.port }}
      name: http
  selector:
    app: {{ include "minimal5gc.fullname" . }}-upf
